name: Continuous deployment
on: push
jobs:
  install-lint:
    name: Install dependencies, check linter, and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository for continuous integration
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install && npm install --dev
      - name: Lint
        run: npm run eslint
      - name: Test
        run: npm run test
